### ISSUE TITLE
Неконсистентное форматирование и описание митапа

### ISSUE THREAD

**Issue by tereshhhchenko** [pitercss/a11y_docs#11]
После обновления описания митапа (https://github.com/pitercss/a11y_docs/pull/7) следует проверить прочие документы, чтобы стиль и форматирование совпадали.

**Comment by TatianaFokina** [comment]
Проверила и слегка исправила: вроде всё теперь консистентно. Можно ещё раз проверить, чтобы всё было наверняка.

**Comment by tereshhhchenko** [comment]
Проверила еще раз, поправила форматирование списков. В целом выглядит хорошо, думаю, можно закрывать. Спасибо за помощь! ✨
