### ISSUE TITLE
Вопросы по гайду для докладчиков

### ISSUE THREAD

**Issue by TatianaFokina** [pitercss/a11y_docs#3]
@HelloDeadline, @pepelsbey и @vasiliydudin 
1. К кому докладчики могут обращаться по вопросу тестирования подключения ноута к проектору?
2. За сколько докладчикам приезжать?
3. Какое оборудование мы им предоставляем? Если они забыли ноут, то чей будет предложен взамен?
4. Нужно ли писать какие-то контакты здесь, по которым докладчики могут с нами связаться?

**Comment by pepelsbey** [comment]
1. Обычно на митапе есть ответственный человек, который разбирается в технике и помогает всё тестировать. Чаще всего это я, поэтому насчёт этого можно обращаться ко мне или тому, кто играет эту роль на митапе.
2. Докладчикам лучше приезжать за полчаса до начала (18:30, если начало в 19:00), чтобы всё проверить.
3. Если заранее непонятно, подключится ли ноут (дикие выходы, не найти переходник), то у организаторов (или у техника, то есть меня) обычно есть свой ноут и его можно включить вместо докладческого. Но это аварийный вариант, а не норм. Оргам нужны свои ноуты во время митапа, надо это выставить требованием докладчику: ноут ваш.
4. Можно написать мои контакты для всех технических вопросов: подключение, вывод звука, кликеры, таймер. Почту и Телеграм.

**Comment by TatianaFokina** [comment]
Пул реквест: https://github.com/pitercss/a11y_docs/pull/5
