### ISSUE TITLE
Указать контакты во всех ридми, где требуется по тексту

### ISSUE THREAD

**Issue by tereshhhchenko** [pitercss/a11y_docs#8]
- Официальную почту
- Ссылку на CFP
- Контакты организаторов
- Контакт для репорта нарушений Норм поведения

**Comment by tereshhhchenko** [comment]
Пока что отсутствие почты и формы CFP — блокер

**Comment by TatianaFokina** [comment]
Везде указана корректная почта.
Контакты организаторов есть в README, нужно где-то ещё? Добавила ещё в анонс.

**Comment by TatianaFokina** [comment]
Ссылки на форму для докладчиков тоже добавила.
